context:
  version: "4.8.3"

package:
  name: shopify-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@shopify/cli/-/cli-${{ version }}.tgz
  sha256: ded3b5cb6eb01f77228c6cece8d0a4712a25a708fd8dc731c927b528bfd03f47

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - shopify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Build apps, themes, and hydrogen storefronts for Shopify
  homepage: https://github.com/Shopify/cli
  repository: https://github.com/Shopify/cli

extra:
  recipe-maintainers:
    - danielnachun
