context:
  name: shopify-cli
  version: "3.92.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@shopify/cli/-/cli-${{ version }}.tgz
  sha256: 3e6b00d5b55301d2622cd9fe7c5927f6626a59898996b17552639e35dad41471

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - shopify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Build apps, themes, and hydrogen storefronts for Shopify
  homepage: https://github.com/Shopify/cli
  repository: https://github.com/Shopify/cli

extra:
  recipe-maintainers:
    - danielnachun
