context:
  name: shopify-cli
  version: "3.86.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@shopify/cli/-/cli-${{ version }}.tgz
  sha256: eb4a2e7ae95318acd2c695fb7902048871bcdffcd8bb3fed11156a894fbf664d

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - shopify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Build apps, themes, and hydrogen storefronts for Shopify
  homepage: https://github.com/Shopify/cli
  repository: https://github.com/Shopify/cli

extra:
  recipe-maintainers:
    - danielnachun
