context:
  version: "4.8.0"

package:
  name: shopify-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@shopify/cli/-/cli-${{ version }}.tgz
  sha256: 67a7975c3a324c8cf173f3adcc49984429501f637ef51c1cb6f940a68671e388

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - shopify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Build apps, themes, and hydrogen storefronts for Shopify
  homepage: https://github.com/Shopify/cli
  repository: https://github.com/Shopify/cli

extra:
  recipe-maintainers:
    - danielnachun
