context:
  name: shopify-cli
  version: "3.81.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@shopify/cli/-/cli-${{ version }}.tgz
  sha256: d35b6443ff77771ff5c351bb6901ed8ee18c5d8e3d644dd7dd19c6894c702f93

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - shopify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Build apps, themes, and hydrogen storefronts for Shopify
  homepage: https://github.com/Shopify/cli
  repository: https://github.com/Shopify/cli

extra:
  recipe-maintainers:
    - danielnachun
